language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: fdoowd1bixXLWPZghT6W6ND6Oh7LyMyEUrQq2nIULYhJxfrxxWkzhyk3YTp/Y3yut1OII9GeU7Ub+JRHirOxe75iNaRToImJtZUqUeFI7OgJBidvhOygPW/dAhWLdWzrV/LjMgh/fN5TNujpIxR9Z7lFN96v3fjMSFi5hMjk5/0X/8FIks701ijQHT0dY/hv03OKKGirNYLnPTgAbFwGLTmR8k4juYPT/QJ2dLEsVZTL1wFg8sW/AHrorlxDNht8z5HyM9FZ6lMZI8LvKCEeFWWTXgSncuRHf7BsRbFfp59NlGrrmqXtxym0WVXrSgRcLRrUJ5pcbg2iq1x6N1L3hXjng/8jTacrD9a1tJcb7sEHxZAAFG4JBZBSxsVPVovtk0d/u06uXXBee6CM8mR6zx4IvVs8VNK/t46Qj7km+v7Tagt6TQ5PJy4TUR+jWfnSKCtoqMamFpKLRfoTRr79ZhBrR5VM4wskVBZNa6smRv+pWpcZia+NEa28J/RNZFnabBtdjr/gihkeHC0l8ao20THNzeBCvdRjHgKrLk9apnWCAWXeJSQNm9XCJYFh97LQt6Cn7jC2qcBXzkqen9OYnaoRrsZE0WGkfWBaFsL1SuI78qqKdUiZPcq5RP2epeeWKgT2FF5GTqqLb2z6gb1kCuSe3nDy7Z4ev6YaeGc0tsY=
  skip_cleanup: true
  app: vast-falls-77512
